// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wxcli.proto

package wxcli

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Field struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Help string `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`
	// Types that are valid to be assigned to Mode:
	//	*Field_ModeFlag
	//	*Field_ModeArg
	//	*Field_ModeEmbedded
	//	*Field_ModeCmd
	//	*Field_ModeCmdname
	Mode                 isField_Mode `protobuf_oneof:"mode"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_133859815ee93a29, []int{0}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

type isField_Mode interface {
	isField_Mode()
}

type Field_ModeFlag struct {
	ModeFlag *Field_Flag `protobuf:"bytes,11,opt,name=mode_flag,json=modeFlag,proto3,oneof"`
}

type Field_ModeArg struct {
	ModeArg *Field_Arg `protobuf:"bytes,12,opt,name=mode_arg,json=modeArg,proto3,oneof"`
}

type Field_ModeEmbedded struct {
	ModeEmbedded *Field_Embedded `protobuf:"bytes,13,opt,name=mode_embedded,json=modeEmbedded,proto3,oneof"`
}

type Field_ModeCmd struct {
	ModeCmd *Field_Cmd `protobuf:"bytes,14,opt,name=mode_cmd,json=modeCmd,proto3,oneof"`
}

type Field_ModeCmdname struct {
	ModeCmdname *Field_CmdName `protobuf:"bytes,15,opt,name=mode_cmdname,json=modeCmdname,proto3,oneof"`
}

func (*Field_ModeFlag) isField_Mode() {}

func (*Field_ModeArg) isField_Mode() {}

func (*Field_ModeEmbedded) isField_Mode() {}

func (*Field_ModeCmd) isField_Mode() {}

func (*Field_ModeCmdname) isField_Mode() {}

func (m *Field) GetMode() isField_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *Field) GetModeFlag() *Field_Flag {
	if x, ok := m.GetMode().(*Field_ModeFlag); ok {
		return x.ModeFlag
	}
	return nil
}

func (m *Field) GetModeArg() *Field_Arg {
	if x, ok := m.GetMode().(*Field_ModeArg); ok {
		return x.ModeArg
	}
	return nil
}

func (m *Field) GetModeEmbedded() *Field_Embedded {
	if x, ok := m.GetMode().(*Field_ModeEmbedded); ok {
		return x.ModeEmbedded
	}
	return nil
}

func (m *Field) GetModeCmd() *Field_Cmd {
	if x, ok := m.GetMode().(*Field_ModeCmd); ok {
		return x.ModeCmd
	}
	return nil
}

func (m *Field) GetModeCmdname() *Field_CmdName {
	if x, ok := m.GetMode().(*Field_ModeCmdname); ok {
		return x.ModeCmdname
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Field) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Field_ModeFlag)(nil),
		(*Field_ModeArg)(nil),
		(*Field_ModeEmbedded)(nil),
		(*Field_ModeCmd)(nil),
		(*Field_ModeCmdname)(nil),
	}
}

//
type Field_Flag struct {
	Short                string   `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Env                  string   `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field_Flag) Reset()         { *m = Field_Flag{} }
func (m *Field_Flag) String() string { return proto.CompactTextString(m) }
func (*Field_Flag) ProtoMessage()    {}
func (*Field_Flag) Descriptor() ([]byte, []int) {
	return fileDescriptor_133859815ee93a29, []int{0, 0}
}

func (m *Field_Flag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_Flag.Unmarshal(m, b)
}
func (m *Field_Flag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_Flag.Marshal(b, m, deterministic)
}
func (m *Field_Flag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_Flag.Merge(m, src)
}
func (m *Field_Flag) XXX_Size() int {
	return xxx_messageInfo_Field_Flag.Size(m)
}
func (m *Field_Flag) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_Flag.DiscardUnknown(m)
}

var xxx_messageInfo_Field_Flag proto.InternalMessageInfo

func (m *Field_Flag) GetShort() string {
	if m != nil {
		return m.Short
	}
	return ""
}

func (m *Field_Flag) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Field_Flag) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

type Field_Arg struct {
	Min                  int32    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field_Arg) Reset()         { *m = Field_Arg{} }
func (m *Field_Arg) String() string { return proto.CompactTextString(m) }
func (*Field_Arg) ProtoMessage()    {}
func (*Field_Arg) Descriptor() ([]byte, []int) {
	return fileDescriptor_133859815ee93a29, []int{0, 1}
}

func (m *Field_Arg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_Arg.Unmarshal(m, b)
}
func (m *Field_Arg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_Arg.Marshal(b, m, deterministic)
}
func (m *Field_Arg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_Arg.Merge(m, src)
}
func (m *Field_Arg) XXX_Size() int {
	return xxx_messageInfo_Field_Arg.Size(m)
}
func (m *Field_Arg) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_Arg.DiscardUnknown(m)
}

var xxx_messageInfo_Field_Arg proto.InternalMessageInfo

func (m *Field_Arg) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Field_Arg) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type Field_Embedded struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field_Embedded) Reset()         { *m = Field_Embedded{} }
func (m *Field_Embedded) String() string { return proto.CompactTextString(m) }
func (*Field_Embedded) ProtoMessage()    {}
func (*Field_Embedded) Descriptor() ([]byte, []int) {
	return fileDescriptor_133859815ee93a29, []int{0, 2}
}

func (m *Field_Embedded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_Embedded.Unmarshal(m, b)
}
func (m *Field_Embedded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_Embedded.Marshal(b, m, deterministic)
}
func (m *Field_Embedded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_Embedded.Merge(m, src)
}
func (m *Field_Embedded) XXX_Size() int {
	return xxx_messageInfo_Field_Embedded.Size(m)
}
func (m *Field_Embedded) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_Embedded.DiscardUnknown(m)
}

var xxx_messageInfo_Field_Embedded proto.InternalMessageInfo

func (m *Field_Embedded) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type Field_Cmd struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field_Cmd) Reset()         { *m = Field_Cmd{} }
func (m *Field_Cmd) String() string { return proto.CompactTextString(m) }
func (*Field_Cmd) ProtoMessage()    {}
func (*Field_Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_133859815ee93a29, []int{0, 3}
}

func (m *Field_Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_Cmd.Unmarshal(m, b)
}
func (m *Field_Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_Cmd.Marshal(b, m, deterministic)
}
func (m *Field_Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_Cmd.Merge(m, src)
}
func (m *Field_Cmd) XXX_Size() int {
	return xxx_messageInfo_Field_Cmd.Size(m)
}
func (m *Field_Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Field_Cmd proto.InternalMessageInfo

type Field_CmdName struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field_CmdName) Reset()         { *m = Field_CmdName{} }
func (m *Field_CmdName) String() string { return proto.CompactTextString(m) }
func (*Field_CmdName) ProtoMessage()    {}
func (*Field_CmdName) Descriptor() ([]byte, []int) {
	return fileDescriptor_133859815ee93a29, []int{0, 4}
}

func (m *Field_CmdName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_CmdName.Unmarshal(m, b)
}
func (m *Field_CmdName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_CmdName.Marshal(b, m, deterministic)
}
func (m *Field_CmdName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_CmdName.Merge(m, src)
}
func (m *Field_CmdName) XXX_Size() int {
	return xxx_messageInfo_Field_CmdName.Size(m)
}
func (m *Field_CmdName) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_CmdName.DiscardUnknown(m)
}

var xxx_messageInfo_Field_CmdName proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Field)(nil), "wxcli.Field")
	proto.RegisterType((*Field_Flag)(nil), "wxcli.Field.Flag")
	proto.RegisterType((*Field_Arg)(nil), "wxcli.Field.Arg")
	proto.RegisterType((*Field_Embedded)(nil), "wxcli.Field.Embedded")
	proto.RegisterType((*Field_Cmd)(nil), "wxcli.Field.Cmd")
	proto.RegisterType((*Field_CmdName)(nil), "wxcli.Field.CmdName")
}

func init() { proto.RegisterFile("wxcli.proto", fileDescriptor_133859815ee93a29) }

var fileDescriptor_133859815ee93a29 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xa5, 0xbf, 0x52, 0xfe, 0x4c, 0xe1, 0x27, 0x6e, 0x20, 0x6e, 0x7a, 0x22, 0x9e, 0xf0, 0x60,
	0x31, 0x7a, 0x32, 0xf1, 0x02, 0x28, 0xe1, 0xe4, 0xa1, 0x47, 0x2f, 0x64, 0x61, 0xd7, 0xa5, 0x49,
	0x97, 0x25, 0x2b, 0x48, 0xbf, 0xb0, 0xdf, 0xc3, 0xcc, 0xb4, 0x25, 0x62, 0xbc, 0xbd, 0x79, 0x7d,
	0xef, 0xcd, 0xbe, 0x49, 0x21, 0x3c, 0xe6, 0xeb, 0x2c, 0x8d, 0x77, 0xce, 0xee, 0x2d, 0x0b, 0x68,
	0xb8, 0xfe, 0xf2, 0x21, 0x98, 0xa7, 0x2a, 0x93, 0x8c, 0x41, 0x7d, 0x2b, 0x8c, 0xe2, 0xde, 0xd0,
	0x1b, 0xb5, 0x13, 0xc2, 0xc8, 0x6d, 0x54, 0xb6, 0xe3, 0xff, 0x0a, 0x0e, 0x31, 0xbb, 0x83, 0xb6,
	0xb1, 0x52, 0x2d, 0xdf, 0x33, 0xa1, 0x79, 0x38, 0xf4, 0x46, 0xe1, 0xfd, 0x65, 0x5c, 0x24, 0x53,
	0x50, 0x3c, 0xcf, 0x84, 0x5e, 0xd4, 0x92, 0x16, 0xaa, 0x10, 0xb3, 0x5b, 0x20, 0xbc, 0x14, 0x4e,
	0xf3, 0x0e, 0x19, 0x7a, 0x67, 0x86, 0x89, 0x43, 0x7d, 0x13, 0x35, 0x13, 0xa7, 0xd9, 0x13, 0x74,
	0x49, 0xae, 0xcc, 0x4a, 0x49, 0xa9, 0x24, 0xef, 0x92, 0x67, 0x70, 0xe6, 0x79, 0x29, 0x3f, 0x2e,
	0x6a, 0x49, 0x07, 0xd5, 0xd5, 0x7c, 0x5a, 0xb6, 0x36, 0x92, 0xff, 0xff, 0x63, 0xd9, 0xcc, 0xc8,
	0x6a, 0xd9, 0xcc, 0x48, 0xf6, 0x08, 0x9d, 0x4a, 0x4e, 0xed, 0x2f, 0xc8, 0xd2, 0xff, 0x6d, 0x79,
	0x15, 0x46, 0x2d, 0x6a, 0x49, 0x58, 0xda, 0x50, 0x1a, 0x3d, 0x43, 0x9d, 0xea, 0xf5, 0x21, 0xf8,
	0xd8, 0x58, 0xb7, 0x2f, 0x2f, 0x57, 0x0c, 0xc8, 0x6a, 0x67, 0x0f, 0xd5, 0xed, 0x8a, 0x81, 0xf5,
	0xc0, 0x57, 0xdb, 0x4f, 0xee, 0x13, 0x87, 0x30, 0xba, 0x01, 0x1f, 0x4b, 0xf7, 0xc0, 0x37, 0xe9,
	0x96, 0x22, 0x82, 0x04, 0x21, 0x31, 0x22, 0x27, 0x3b, 0x32, 0x22, 0x8f, 0x86, 0xd0, 0x3a, 0xd5,
	0x3c, 0xc5, 0x7b, 0x3f, 0xe2, 0xa3, 0x00, 0xfc, 0x99, 0x91, 0x51, 0x1b, 0x9a, 0xe5, 0x9b, 0xa7,
	0x0d, 0xa8, 0xe3, 0x9b, 0xa7, 0x57, 0x6f, 0x03, 0x9d, 0xee, 0x37, 0x87, 0x55, 0xbc, 0xb6, 0x66,
	0x7c, 0xcc, 0x53, 0x3b, 0xa6, 0x8a, 0xab, 0x06, 0xfd, 0x0e, 0x0f, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x4f, 0x8b, 0x3c, 0xde, 0x1d, 0x02, 0x00, 0x00,
}
